version: "3"

tasks:
  create:
    desc: create new project from template
    cmds:
      - |
        echo "プロジェクト名を入力してください"
        read PROJECT_NAME;
        copier copy --vcs-ref=main --data project_name=${PROJECT_NAME} https://github.com/ogontaro/templates_template.git templates/${PROJECT_NAME};
        mv templates/${PROJECT_NAME}/template/.copier-answers.yml answers/.copier-answers.${PROJECT_NAME}.yml
        echo "${PROJECT_NAME} created";
  update:
    desc: update project from template
    cmds:
      - |
        echo "更新するプロジェクトを選択してください："
        select PROJECT_NAME in $(ls answers/*.copier-answers.yml | xargs -n 1 basename | sed 's/\.copier-answers\.yml//'); do
          if [ -n "$PROJECT_NAME" ]; then
            copier update --vcs-ref=main --skip-answered templates/${PROJECT_NAME} --answers-file ../../answers/.copier-answers.${PROJECT_NAME}.yml
            echo "${PROJECT_NAME} を更新しました"
            break
          else
            echo "無効な選択です。もう一度お試しください。"
          fi
        done
        echo "${PROJECT_NAME} updated";
  delete:
    desc: delete project from template
    cmds:
      - |
        echo "削除するプロジェクト名を選択してください"
        select PROJECT_NAME in $(ls answers/*.copier-answers.yml | xargs -n 1 basename | sed 's/\.copier-answers\.yml//'); do
          if [ -n "$PROJECT_NAME" ]; then
            rm -rf templates/${PROJECT_NAME}
            rm -rf answers/.copier-answers.${PROJECT_NAME}.yml
            echo "${PROJECT_NAME} deleted"
            break
          else
            echo "無効な選択です。もう一度お試しください。"
          fi
        done
  create:test:
    desc: test create new project from template
    cmds:
      - |
        copier copy --vcs-ref=main --data project_name=go https://github.com/ogontaro/templates_template.git templates/go
        mv templates/go/.copier-answers.yml answers/.copier-answers.go.yml
  update:test:
    desc: test update project from template
    cmds:
      - copier update --vcs-ref=main --skip-answered templates/go --answers-file ../../answers/.copier-answers.go.yml
  delete:test:
    desc: test delete project from template
    cmds:
      - rm -rf templates/go
      - rm -rf answers/.copier-answers.go.yml
