# TODO Fill in the helmfile for the {{cookiecutter.project_name}} project
#  fill __REPOSITORY_NAME__
#  fill __REPOSITORY_URL__
#  fill __SERVICE_URL__
#  fill __SERVICE_VERSION__
environments:
  sandbox:
    values:
      - environments.sandbox.yaml
  production:
    values:
      - environments.production.yaml
---
repositories:
  - name: __REPOSITORY_NAME__
    url: __REPOSITORY_URL__

releases:
  - name: my-chart
    installed: { % raw % }{{ .Values.enabled }}{ % endraw % }
    namespace: {{cookiecutter.project_name}}
    chart: ./chart
  - name: {{cookiecutter.project_name}}
    installed: { % raw % }{{ .Values.enabled }}{ % endraw % }
    namespace: {{cookiecutter.project_name}}
    chart: __REPOSITORY_NAME__/__SERVICE_NAME__
    version: __SERVICE_VERSION__
    values:
      - values.yaml.gotmpl
    needs:
      - my-chart
