init:
	task init
.PHONY: init

service.start:
	task service:start
.PHONY: service.start

service.stop:
	task service:stop
.PHONY: service.stop

service.clean:
	task service:clean
.PHONY: service.clean
