init:
	task init
.PHONY: init

service_start:
	task service:start
.PHONY: service_start

service_stop:
	task service:stop
.PHONY: service_stop

service_clean:
	task service:clean
.PHONY: service_clean
