init:
	task init
.PHONY: init

service.start:
	task service:start
.PHONY: service.start

service.stop:
	task service:stop
.PHONY: service.stop

service.clean:
	task service:clean
.PHONY: service.clean

mutagen.start:
	task mutagen:start
.PHONY: mutagen.start

mutagen.status:
	task mutagen:status
.PHONY: mutagen.status

mutagen.stop:
	task mutagen:stop
.PHONY: mutagen.stop
