name: Subtree Pull

on:
  repository_dispatch:
    types: [ subtree-pull ]

jobs:
  triggered-job:
    runs-on: [ templates-runners ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 全ての履歴をクローン

      - name: Set up Git credentials
        run: |
          git config --global user.email "$(git log -1 --pretty=format:'%ae')"
          git config --global user.name "$(git log -1 --pretty=format:'%an')"

      - name: Pull from subtrees
        env:
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
        run: |
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          
          git clone https://ogontaro:${GIT_ACCESS_TOKEN}@github.com/ogontaro/templates.git work && cd work
          git checkout $GITHUB_SHA
          git remote add ogontaro_infra https://ogontaro:${GIT_ACCESS_TOKEN}@github.com/ogontaro/templates_ogontaro_infra
          git remote add application https://ogontaro:${GIT_ACCESS_TOKEN}@github.com/ogontaro/templates_application

          GIT_EDITOR=true git subtree pull --prefix=templates/ogontaro_infra ogontaro_infra main
          GIT_EDITOR=true git subtree pull --prefix=templates/application templates_application main
          git push origin main
