name: Subtree Push

on:
  push:
    branches-ignore:
      - production
      - staging

jobs:
  push-subtrees:
    runs-on: templates-runners

    steps:
      - name: Install Git
        run: |
          sudo apt-get update
          sudo apt-get install -y git

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 全ての履歴をクローン

      - name: List directory contents
        run: |
          pwd
          ls -la

      - name: Set up Git credentials
        env:
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
        run: |
          git_email=$(git log -1 --pretty=format:'%ae')
          git_name=$(git log -1 --pretty=format:'%an')
          
          # emailとnameを設定
          git config --global user.email "$git_email"
          git config --global user.name "$git_name"

          git remote add ogontaro_infra https://x-access-token:${GIT_ACCESS_TOKEN}@github.com/ogontaro/templates_ogontaro_infra.git
          git remote add application https://x-access-token:${GIT_ACCESS_TOKEN}@github.com/ogontaro/templates_application.git

      - name: Push to subtrees
        env:
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
        run: |
          git fetch origin
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          
          # templates/ogontaro_infraディレクトリの変更を確認
          if git diff --quiet HEAD^ HEAD -- templates/ogontaro_infra; then
              echo "No changes in templates/ogontaro_infra"
          else
              git subtree push --prefix=templates/ogontaro_infra https://x-access-token:${GIT_ACCESS_TOKEN}@github.com/ogontaro/templates_ogontaro_infra.git $current_branch
          fi
          
          # templates/applicationディレクトリの変更を確認
          if git diff --quiet HEAD^ HEAD -- templates/application; then
              echo "No changes in templates/application"
          else
              git subtree push --prefix=templates/application https://x-access-token:${GIT_ACCESS_TOKEN}@github.com/ogontaro/templates_application.git $current_branch
          fi
