name: Subtree Push

on:
  push:
    branches-ignore:
      - production
      - staging

jobs:
  push-subtrees:
    runs-on: [ ogontaro-infra-runners ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 全ての履歴をクローン

      - name: Set up Git credentials
        run: |
          git config --global user.email "$(git log -1 --pretty=format:'%ae')"
          git config --global user.name "$(git log -1 --pretty=format:'%an')"

      - name: Push to subtrees
        env:
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
        run: |
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          
          git clone https://ogontaro:${GIT_ACCESS_TOKEN}@github.com/ogontaro/templates.git work && cd work
          git checkout $GITHUB_SHA
          git remote add ogontaro_infra https://ogontaro:${GIT_ACCESS_TOKEN}@github.com/ogontaro/templates_ogontaro_infra
          git remote add application https://ogontaro:${GIT_ACCESS_TOKEN}@github.com/ogontaro/templates_application

          # templates/ogontaro_infraディレクトリの変更を確認
          if git diff --quiet HEAD^ HEAD -- templates/ogontaro_infra; then
              echo "No changes in templates/ogontaro_infra"
          else
              git subtree push --prefix=templates/ogontaro_infra ogontaro_infra $current_branch
          fi
          
          # templates/applicationディレクトリの変更を確認
          if git diff --quiet HEAD^ HEAD -- templates/application; then
              echo "No changes in templates/application"
          else
              git subtree push --prefix=templates/application application $current_branch
          fi
