name: Sync to application repository

on:
  push:
    paths:
      - 'templates/application/**'

jobs:
  sync:
    runs-on: ogontaro-runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Push changes to awesome_web
        if: contains(github.event.head_commit.message, 'awesome_web')
        run: |
          git clone git@github.com:username/awesome_web.git temp_web
          cp -r awesome_web/* temp_web/
          cd temp_web
          git add .
          git commit -m "Sync from parent repo: ${GITHUB_SHA}"
          git push origin main

      - name: Push changes to awesome_backend
        if: contains(github.event.head_commit.message, 'awesome_backend')
        run: |
          git clone git@github.com:username/awesome_backend.git temp_backend
          cp -r awesome_backend/* temp_backend/
          cd temp_backend
          git add .
          git commit -m "Sync from parent repo: ${GITHUB_SHA}"
          git push origin main
